Add CRUD features
elassis/webpack_project pull request #4
Opened 2021-07-24 01:54 UTC by elassis

# What I Have Accomplished 🏆 : 

* Create element feature
* Update element feature
* Delete element feature
* Delete all elements at once feature

# Built With ⚒️ : 
* CSS
* HTML
* Javascript
* Webpack

2021-07-24 02:18 UTC, mricanho requested changes
Hi @elassis, 

It's a good first attempt for this milestone.

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] Like I told you on your last milestone, you need to rework all your README file, it's not professional and it describes barely something about your app. Remember that you need to add a "Set up" section and step-by-step instructions about how to run your project locally. [Open this link to refresh all the whys](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

- [ ]  Something brokes since your last milestone, the app doesn't accept a new task and since then I can't check any other behavior, so the next Code Reviewer must test all the behavior of your app on your next CR request, remember that before you submit your project you must double-check if your app runs.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![easyday](https://user-images.githubusercontent.com/60631456/126854720-23d0694d-6e39-4e97-8f5e-6be40244447b.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-24 02:18 UTC, mricanho commented on src/crud.js
> +  });
- [ ] This function it's not working, debug and try again with a new approach, check your chrome tool for the error

![imagen](https://user-images.githubusercontent.com/60631456/126854568-37b9828b-5810-484c-8fba-73b0979e07eb.png)

2021-07-24 03:38 UTC, MahmoudBakr23 requested changes
Hi @elassis😃, 

Well done implementing the README file requested changes 💯 
The changes requested from the previous review haven't been implemented yet. Please make sure to do all the changes before you request another CRR 😄🙏 

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️

- [ ] Please go through the comments below and the previous review comments once again

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

_Please see the inline comments down below._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-24 03:38 UTC, MahmoudBakr23 commented on .gitignore
> +.vscode/
- [ ] **OPTIONAL**
Kindly double-check on this file because it's still loaded within the files.
_Please note that only the files relevant to the project should be committed to the GitHub repo_

2021-07-24 03:38 UTC, MahmoudBakr23 commented on src/crud.js
> +    if (e.key === 'Enter' && e.target.id === 'main-input' && e.target.value !== '') {
- [ ] The tasks are still can't be added. Please fix this issue as the previous reviewer mentioned!
I highly suggest that you build your changes locally and test them before you commit the changes_

2021-07-24 10:50 UTC, elassis commented on src/crud.js
> +    if (e.key === 'Enter' && e.target.id === 'main-input' && e.target.value !== '') {
Hello, kindly check the live preview link in my comment at the top or the readme link and you will see that the system is running correctly  thank you

2021-07-24 12:30 UTC, MahmoudBakr23 commented on src/crud.js
> +    if (e.key === 'Enter' && e.target.id === 'main-input' && e.target.value !== '') {
Thank you for contacting me 😊 Please note that when I build the app locally I found out that I can't add new tasks, but in the live demo link, I can do that. However, there are a few issues I faced with the live demo version, first, the clean completed button is deleting all the tasks even the unchecked tasks, and second is when a task is removed and another one is added, it come back again within the list!
Please reach out again in case of any questions 😊🙏🏻

2021-07-26 15:02 UTC, mricanho requested changes
Hi @elassis, 

Your project's nearly finished.

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] **Three times I've been told you that you need to rework all your README file, it's not professional and it describes barely something about your app. Remember that you need to add a "Set up" section and step-by-step instructions about how to run your project locally. [Open this link to refresh all the whys](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).**

Your README file:

![image](https://user-images.githubusercontent.com/60631456/127010631-f96719af-d970-423c-9a04-de5854c225d5.png)

The mandatory section that your README file lacks:

![image](https://user-images.githubusercontent.com/60631456/127010950-5b5ddb71-37cd-4d3b-9d50-84b98bc5fc9a.png)

**[HERE IS THE LINK OF THE TEMPLATE](https://github.com/microverseinc/readme-template)**

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![fix it](https://user-images.githubusercontent.com/60631456/127011610-27741c9f-986c-4740-a5e0-247a0db581d8.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-26 16:46 UTC, mricanho commented on src/status.js
>  }
Hi @elassis,

Thanks for reaching out, you need to open a new PR for the next milestones, every time you repeat a week, you need to do that. Fresh PR is mandatory to avoid this kind of conflict, for now, you can use this PR for your next code review, even though the review about the behavior of your app it's irrelevant the README file it's mandatory in every milestone, so go ahead and work on that.

2021-07-26 18:04 UTC, closed without merging